// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiCEzTmtaQQ6aTl93IMIQmjGmXlvrA548',
    appId: '1:35499122175:web:ede10ca7fb499d017c5bca',
    messagingSenderId: '35499122175',
    projectId: 'air-2204',
    authDomain: 'air-2204.firebaseapp.com',
    storageBucket: 'air-2204.appspot.com',
    measurementId: 'G-RG6T027WEV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdsm2yV1jpWQOJTbgw6HSuaHP3_we_7Gw',
    appId: '1:35499122175:android:4096c4b77860caa87c5bca',
    messagingSenderId: '35499122175',
    projectId: 'air-2204',
    storageBucket: 'air-2204.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAbFkt8sHHa0EB4AmKFmsI3-_P_zJq0rA',
    appId: '1:35499122175:ios:2c19cadc26017abf7c5bca',
    messagingSenderId: '35499122175',
    projectId: 'air-2204',
    storageBucket: 'air-2204.appspot.com',
    iosClientId: '35499122175-uladmafqni4f27qok0q0bncaer2rte5t.apps.googleusercontent.com',
    iosBundleId: 'com.deep.conference.deepConference',
  );
}
