// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLLG8hh2yGYZbMoDxRuipDkToqaA4O9Ts',
    appId: '1:797969937440:web:4d55b17fcbdd45d62ff845',
    messagingSenderId: '797969937440',
    projectId: 'air-2204-test',
    authDomain: 'air-2204-test.firebaseapp.com',
    databaseURL: 'https://air-2204-test-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'air-2204-test.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPxJ69Kf8wcZTX5CZ-25T9OfVghWVfSP0',
    appId: '1:797969937440:android:956f2eedb486488b2ff845',
    messagingSenderId: '797969937440',
    projectId: 'air-2204-test',
    databaseURL: 'https://air-2204-test-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'air-2204-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXHLMRajnS8CFw25ejEg0skF6cQGOmCeQ',
    appId: '1:797969937440:ios:f736df653e40be5b2ff845',
    messagingSenderId: '797969937440',
    projectId: 'air-2204-test',
    databaseURL: 'https://air-2204-test-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'air-2204-test.appspot.com',
    iosClientId: '797969937440-n2ao8hisustq6ofnj7p84d3g3d5dcn2u.apps.googleusercontent.com',
    iosBundleId: 'com.example.expandableAttempt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXHLMRajnS8CFw25ejEg0skF6cQGOmCeQ',
    appId: '1:797969937440:ios:f736df653e40be5b2ff845',
    messagingSenderId: '797969937440',
    projectId: 'air-2204-test',
    databaseURL: 'https://air-2204-test-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'air-2204-test.appspot.com',
    iosClientId: '797969937440-n2ao8hisustq6ofnj7p84d3g3d5dcn2u.apps.googleusercontent.com',
    iosBundleId: 'com.example.expandableAttempt',
  );
}
